### ISSUE TITLE
Latest Docker Image ghcr.io/mergestat/sync-github-pull-requests:sha-6defb5b Not Functioning

### ISSUE THREAD

**Issue by na0x2c6** [mergestat/syncs#69]
Hello,

I am facing an issue with the `latest` version of the Docker image provided by this repository (`ghcr.io/mergestat/sync-github-pull-requests:sha-6defb5b`). It seems to be not functioning as expected.

Here are the error logs I encountered:

```
05/28/2023 19:58:28 DEBUG: running sync 56b2c8bd-78d7-4b8d-a63d-b8e0fe362c59
05/28/2023 19:58:28 INFO: pulling image docker://ghcr.io/mergestat/sync-github-pull-requests:latest
05/28/2023 19:58:38 INFO: running image docker://ghcr.io/mergestat/sync-github-pull-requests:latest
05/28/2023 19:58:38 DEBUG: [Package Error] "lru-cache@v9.1.1" could not be built. (Imported by "@octokit/auth-app").
05/28/2023 19:58:38 DEBUG: [1/5] Verifying package is valid…
05/28/2023 19:58:38 DEBUG: [2/5] Installing dependencies from npm…
05/28/2023 19:58:38 DEBUG: [3/5] Building package using esinstall…
05/28/2023 19:58:38 DEBUG: Running esinstall...
05/28/2023 19:58:38 DEBUG: Failed to load node_modules/lru-cache/dist/mjs/index.js
05/28/2023 19:58:38 DEBUG:   Unexpected token (406:4) in lru-cache/dist/mjs/index.js
05/28/2023 19:58:38 DEBUG: Install failed.
05/28/2023 19:58:38 DEBUG: Install failed.
05/28/2023 19:58:38 DEBUG: [0m[1m[31merror[0m: Uncaught Error: [Package Error] "lru-cache@v9.1.1" could not be built. (Imported by "@octokit/auth-app").
05/28/2023 19:58:38 DEBUG: throw new Error("[Package Error] \"lru-cache@v9.1.1\" could not be built. (Imported by \"@octokit/auth-app\").");
05/28/2023 19:58:38 DEBUG: [0m[31m      ^[0m
05/28/2023 19:58:38 DEBUG:     at [0m[36mhttps://cdn.skypack.dev/error/build:lru-cache@v9.1.1-t7cOEoLX2RvAxMKlhTnV?from=@octokit/auth-app[0m:[0m[33m20[0m:[0m[33m7[0m
05/28/2023 19:58:38 ERROR: failed to run image: exit status 1
```

As a workaround, I was able to get things working again by reverting back to the previous image version, specifically `ghcr.io/mergestat/sync-github-pull-requests:sha-304df07`.

Thanks.

**Comment by riyaz-ali** [comment]
@na0x2c6 thanks for the report 👍 

This seems like an issue with the upstream [`skypack.dev`](https://skypack.dev) service which we use to load `deno` modules. The upstream issue is being tracked under skypackjs/skypack-cdn#354.

 @patrickdevivo @amenowanna I think a quick (and maybe long-term?) fix for us could be to use another service (like [`esm.sh`](https://esm.sh) or [`jsdelivr.com`](https://jsdelivr.com)) to load our modules.

**Comment by amenowanna** [comment]
@na0x2c6 we found another issue with OAuth on the last set of changes. We have published a fix for that as well. If you could check the latest version of the syncs things should work. Please let us know either way. Thank you!

**Comment by na0x2c6** [comment]
@amenowanna @riyaz-ali 
I have successfully verified the operation with the new latest tag image (`9f4e1b6d2f67`). Thank you for your work!
